name: chat_client_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.2.1
  dartz: ^0.10.1
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.1.0
  fluttertoast: ^8.0.9
  freezed: ^2.0.3+1
  chat_client_service:
    path: ../chat_client_service

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.1.0
  mocktail: ^0.3.0
  json_serializable: ^6.2.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
