name: my_chat_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed: ^2.0.3+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  chat_app_client:
    path: packages/chat_app_client
  flutter_svg: ^1.1.1+1
  firebase_auth: ^3.4.1
  firebase_storage: ^10.3.1
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  image_picker: ^0.8.5+3
  fluttertoast: ^8.0.9
  get: ^4.6.5
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
