name: chat_app_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.1.0
  fluttertoast: ^8.0.9
dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
